meta_product_name: "La fin des grandes différences"
meta_title: "La fin des grandes différences, par Jean-Pierre Chebassier"
meta_description: "Cent portraits de l'humanité. Pour faire surgir l'invraisemblable diversité humaine telle qu'elle existe encore aujourd'hui, et respecter la différence."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: ""   # required for Twitter Cards